using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Basket : MonoBehaviour
{
    public ScoreCounter scoreCounter;
    public RoundCounter roundCounter;

    // Start is called before the first frame update
    void Start()
    {
        //Find a GameObject named ScoreCounter in the Scene Hierarchy
        GameObject scoreGO = GameObject.Find("ScoreCounter");
        //Find a GameObject named RoundCounter in the scene Hierarchy
        GameObject roundGO = GameObject.Find("RoundCounter");
        // Get the ScoreCounter (Script) component of scoreGO
        scoreCounter = scoreGO.GetComponent<ScoreCounter>();
        //Get the RoundCounter (Script) component of roundGO
        roundCounter = roundGO.GetComponent<RoundCounter>();
    }

    // Update is called once per frame
    void Update()
    {
        // Get the current screen position of the mouse from Input
        Vector3 mousePos2D = Input.mousePosition;

        // The Camera's z position sets how far to push the mouse into 3D
        // If this line causes a NullReferenceException, select the Main Camera
        // in the Hierarchy and set its tag to MainCamera in the Inspector.
        mousePos2D.z = -Camera.main.transform.position.z;

        // Convert the point from 2D screen space into 3D game world space
        Vector3 mousePos3D = Camera.main.ScreenToWorldPoint(mousePos2D);

        // Move the x position of this Basket to the x position of the Mouse
        Vector3 pos = this.transform.position;
        pos.x = mousePos3D.x;
        this.transform.position = pos;
    }

    void OnCollisionEnter(Collision coll)
    {
        // Find out what hit this basket
        GameObject collidedWith = coll.gameObject;
        if (collidedWith.CompareTag("Apple"))
        {
            Destroy(collidedWith);
            // Increase the score
            scoreCounter.score += 100;
            HighScore.TRY_SET_HIGH_SCORE(scoreCounter.score);
            //Set round to modulo 200 of scoreCounter + 1. If it is 5, end the game.
            //To increase/decrease the length of rounds, change the divisor number
            int temp = scoreCounter.score / 400 + 1;
            //Use a switch for faster processing
            switch (temp)
            {
                case 5:
                    SceneManager.LoadScene("GameoverScene");
                    break;
                default:
                    roundCounter.round = temp;
                    break;
            }
        }
        if(collidedWith.CompareTag("Branch"))
        {
            SceneManager.LoadScene("GameoverScene");
        }
    }
}
